all :
	cd h2o-lsq ; make all
	cd h2o-md ; make all
	cd h2o-nonlin ; make all
	cd lsq2 ; make all
	cd gather-force ; make all
	cd openmx ; make all
	cd test-force ; make all

clean :
	cd h2o-lsq ; make clean
	cd h2o-md ; make clean
	cd h2o-nonlin ; make clean
	cd lsq2 ; make clean
	cd gather-force ; make clean
	cd openmx ; make clean
	cd test-force ; make clean

realclean :
	cd h2o-lsq make realclean
	cd h2o-md make realclean
	cd h2o-nonlin ; make realclean
	cd lsq2 ; make realclean
	cd gather-force ; make realclean
	cd openmx ; make realclean
	cd test-force ; make realclean
