all :
	cd h2o-spline ; make all
	cd h2o-md ; make all
	cd h2o-nonlin ; make all

clean :
	cd h2o-spline ; make clean
	cd h2o-md ; make clean
	cd h2o-nonlin ; make clean

realclean :
	cd h2o-spline make realclean
	cd h2o-md make realclean
	cd h2o-nonlin ; make realclean
