all :
	../../bin/nrfit -g deluge.in < nrfit.in >& nrfit.out

clean :
	rm -f A.txt b.txt error.out force.txt gcoeff.out nrfit.out overcoord.in params.header params.over.txt splines_ls.out splines_over.in

