all :
	cd estane ; make estanetest
	cd benzene ; make benzenetest
	cd h2o ; make h2otest
	cd tatb ; make tatbtest 
	cd estane.skip ; make estanetest
	cd h2o.skip ; make h2otest

clean :
	cd estane ; make clean
	cd benzene ; make clean
	cd h2o ; make clean
	cd tatb ; make clean
	cd estane.skip ; make clean
	cd h2o.skip ; make clean
