all:
	cd lsq ; make all
	cd mdcode ; make all
	cd nrfit ; make all

clean:
	cd lsq ; make clean
	cd mdcode ; make clean
	cd nrfit ; make clean

realclean:
	cd lsq ; make realclean
	cd mdcode ; make realclean
	cd nrfit ; make realclean
	rm -f ../bin/splines_md ../bin/splines_ls
